name: Testing with devbox

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.9.0

      - name: Run arbitrary commands
        run: devbox run -- echo "done!"

      - name: Check Devbox Java (JDK) version
        run: devbox info jdk22
        
      - name: Check Devbox Maven version
        run: devbox info maven
        
      - name: Run mvn tests
        run: devbox run test
