permissions:
  contents: read
name: Testing with devbox

on:
  push: # Trigger on any push to any branch
  schedule:
    - cron: '45 23 * * *' # Run daily at 23:45 UTC

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.15.0
        with:
          enable-cache: 'true' # Cache Nix store

      - name: Check Devbox Java (JDK) version
        run: devbox run -- java -version
        
      - name: Check Devbox Maven version
        run: devbox info maven
        
      - name: Run mvn tests
        run: devbox run test
