name: Testing with devbox

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.9.0

      - name: Run arbitrary commands
        run: devbox run -- echo "done!"

      - name: Switch to Devbox shell
        run: devbox shell

      - name: Check Java version
        run: java --version
        
      - name: Check Maven version
        run: mvn --version
        
      - name: Run mvn tests
        run: devbox run test
